version: "3.9"
services:

  ui:
    build: ./frontend
    container_name: "check24-frontend_container"
    ports:
      - '80:3000'
    depends_on:
      - api

  api:
    build: ./backend
    container_name: "check24-backend_container"
    ports:
      - '4000:4000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    command: mongod --noauth
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodbdata:
    external: true