version: "3.9"
services:

  ui:
    build: ./frontend
    container_name: "check24-frontend_container"
    ports:
      - '80:3000'
    depends_on:
      - api
  api:
    build: ./backend
    container_name: "check24-backend_container"
    ports:
      - '4000:4000'
    depends_on:
      - db

  db:
    build: ./database
    ports:
      - '27107:27107'
    volumes:
      - mongo_db_data2:/data/db


volumes:
  mongo_db_data2: {}